name: workflow.yml
on:
  push:
    branches:
      - main

jobs:
  integration:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Fetch all history for accurate results of code analysis

      - name: Install required tools
        run: |
          dotnet tool install -g dotnet-sonarscanner
          dotnet tool install -g dotnet-reportgenerator-globaltool
          dotnet tool install -g dotnet-stryker
          
      - name: Start Static Code Analysis
        run: |
          dotnet sonarscanner begin \
          /k:"AJG-Calculator-Code-Base" \
          /d:sonar.host.url="http://62.164.217.208:9000/" \
          /d:sonar.token="sqp_aa019f014ce23fbeb597c1393635db783d8ed577" \
          /d:sonar.coverageReportPaths="coverage-report/SonarQube.xml" \
          /d:sonar.qualitygate.wait=true \
          /d:sonar.qualitygate.timeout=300
          
      - name: Build
        run: dotnet build

      - name: Run unit tests
        run: |
          dotnet test --collect:"XPlat Code Coverage" --results-directory TestResults
          
      - name: Generate report
        run: |
          reportgenerator -reports:"TestResults/**/coverage.cobertura.xml" \
          -targetdir:coverage-report \
          -reporttypes:Html \
          
          
      - name: Generate Sonar Report
        run: |
          reportgenerator -reports:"TestResults/**/coverage.cobertura.xml" \
          -targetdir:coverage-report \
          -reporttypes:SonarQube \
        
          
      - name: Complete Static Code Analysis
        run: |
          dotnet sonarscanner end \
          /d:sonar.token="sqp_aa019f014ce23fbeb597c1393635db783d8ed577"
          

      - name: Run Mutation Tests
        run: |
          dotnet stryker --break-at 80

      - name: Collect Coverage Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: Coverage Report
          path: coverage-report

      - name: Collect Stryker Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: Stryker Report
          path: StrykerOutput
        # Complete this step so it uploads the Stryker report to the artifacts - make it run always even if previous 
    